DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS OrderProduct;
DROP TABLE IF EXISTS "Order";
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS market;
DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS product;

