// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: product.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
   category_id,
   brand_id,
   market_id,
   proname,
   description,
   imageurl,
   price,
   quantity
   
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, category_id, brand_id, market_id, proname, description, imageurl, price, quantity
`

type CreateProductParams struct {
	CategoryID  int64   `json:"category_id"`
	BrandID     int64   `json:"brand_id"`
	MarketID    int64   `json:"market_id"`
	Proname     string  `json:"proname"`
	Description string  `json:"description"`
	Imageurl    string  `json:"imageurl"`
	Price       float64 `json:"price"`
	Quantity    int64   `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.CategoryID,
		arg.BrandID,
		arg.MarketID,
		arg.Proname,
		arg.Description,
		arg.Imageurl,
		arg.Price,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BrandID,
		&i.MarketID,
		&i.Proname,
		&i.Description,
		&i.Imageurl,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const deleteProducts = `-- name: DeleteProducts :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProducts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProducts, id)
	return err
}

const getProducts = `-- name: GetProducts :one
SELECT id, category_id, brand_id, market_id, proname, description, imageurl, price, quantity FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProducts(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProducts, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BrandID,
		&i.MarketID,
		&i.Proname,
		&i.Description,
		&i.Imageurl,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, brand_id, market_id, proname, description, imageurl, price, quantity FROM products
ORDER BY proname
LIMIT $1
OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BrandID,
			&i.MarketID,
			&i.Proname,
			&i.Description,
			&i.Imageurl,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET proname = $2
WHERE id = $1
RETURNING id, category_id, brand_id, market_id, proname, description, imageurl, price, quantity
`

type UpdateProductParams struct {
	ID      int64  `json:"id"`
	Proname string `json:"proname"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct, arg.ID, arg.Proname)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BrandID,
		&i.MarketID,
		&i.Proname,
		&i.Description,
		&i.Imageurl,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}
